#!/bin/bash
# Bash completion for arxivdl_cli.py
# Generated by setup_autocompletion.py

_arxivdl_cli_completion() {
    local cur prev words cword
    
    # Get completion variables manually since _init_completion may not be available
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    words=("${COMP_WORDS[@]}")
    cword=${COMP_CWORD}

    # Main commands
    local commands="download convert translate organize analyze inventory setup workflow"

    # Special options
    local options="--help --samples --list --version"

    case $cword in
        1)
            # Complete main commands and options
            COMPREPLY=($(compgen -W "$commands $options" -- "$cur"))
            return 0
            ;;
        2)
            # Complete subcommands based on main command
            case $prev in
                download)
                    COMPREPLY=($(compgen -W "single batch crawler" -- "$cur"))
                    return 0
                    ;;
                convert)
                    COMPREPLY=($(compgen -W "main" -- "$cur"))
                    return 0
                    ;;
                translate)
                    COMPREPLY=($(compgen -W "openai claude check add-queue cleanup process-stalled" -- "$cur"))
                    return 0
                    ;;
                organize)
                    COMPREPLY=($(compgen -W "enhanced basic simple" -- "$cur"))
                    return 0
                    ;;
                analyze)
                    COMPREPLY=($(compgen -W "duplicates translations monitor status" -- "$cur"))
                    return 0
                    ;;
                inventory)
                    COMPREPLY=($(compgen -W "create update check" -- "$cur"))
                    return 0
                    ;;
                setup)
                    COMPREPLY=($(compgen -W "init config test" -- "$cur"))
                    return 0
                    ;;
            esac
            ;;
        *)
            # Complete files for remaining arguments
            case ${words[1]} in
                download)
                    # Complete .txt files for download command
                    COMPREPLY=($(compgen -f -X '!*.txt' -- "$cur"))
                    ;;
                convert)
                    # Complete .pdf files for convert command
                    COMPREPLY=($(compgen -f -X '!*.pdf' -- "$cur"))
                    ;;
                translate)
                    # Complete .txt files for translate command
                    COMPREPLY=($(compgen -f -X '!*.txt' -- "$cur"))
                    ;;
                *)
                    # Default file completion
                    COMPREPLY=($(compgen -f -- "$cur"))
                    ;;
            esac
            ;;
    esac
}

# Register completion function
complete -F _arxivdl_cli_completion arxivdl_cli.py
complete -F _arxivdl_cli_completion python3 arxivdl_cli.py
